name: 'Release Notes Action'
description: 'Get Release notes from JIRA tickets founds in commits'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-key }}